outdir: "results"

# Restriction design (kept unchanged)
design:
  dir: "design/mm10_HindIII"
  rmap: "design/mm10_HindIII/MM10_HindIII.rmap"
  baitmap: "design/mm10_HindIII/MM10_HindIII.baitmap"
  probeinfo: "design/mm10_HindIII/MM10_HindIII_ProbeInfo.txt"

# Per-sample FASTQs (absolute or relative paths). Add as many samples as you like.
samples:
  SampleA:
    r1: "data/SampleA_R1.fastq.gz"
    r2: "data/SampleA_R2.fastq.gz"
  SampleB:
    r1: "data/SampleB_R1.fastq.gz"
    r2: "data/SampleB_R2.fastq.gz"

# HiCUP + mapping settings
hicup:
  bowtie2_bin: "/usr/bin/bowtie2"          # full path to bowtie2 executable
  index: "/refs/bowtie2/mm10"              # bowtie2 index basename (no .bt2 suffix)
  digest: "design/mm10_HindIII/mm10_HindIII_digest.txt"
  threads: 10
  zip: 1                                   # 1=compress outputs, 0=don’t
  keep: 0                                  # 1=keep intermediates
  quiet: 1                                 # 1=suppress progress
  longest: 2000
  shortest: 100
  format: ""                               # usually let HiCUP auto-detect

tools:
  rscript: "Rscript"
  hicup: "hicup"                           # in PATH or full path
  bedtools: "bedtools"
  perl: "perl"
  bam_to_fragments: "scripts/BamToFragments.pl"
  bam2juicer: "scripts/Bam2Juicer.pl"
  align2ibed: "scripts/align2ibed.pl"
  java: "java"
  juicer_tools: "juicer_tools.jar"

params:
  juicer_mem_gb: 10
  juicer_q: 10
  juicer_genome_id: "mm10"
  fanc_resolution: "10kb"
  fanc_balancing: "KR"
  fanc_windows: ["0.5mb","1mb","1.5mb","2mb","2.5mb"]

threads:
  default: 4
