outdir: "results"

# Restriction design (kept unchanged)
design:
  dir: "design/MM10_HindIII"
  rmap: "design/MM10_HindIII/MM10_HindIII.rmap"
  baitmap: "design/MM10_HindIII/MM10_HindIII.baitmap"
  probeinfo: "design/MM10_HindIII/MM10_HindIII_ProbeInfo.txt"

# Per-sample FASTQs (absolute or relative paths). Add as many samples as you like.
samples:
  CI1:
    r1: "data/CI1_R1.fastq.gz"
    r2: "data/CI1_R2.fastq.gz"

hicup:
  bowtie2_bin: "/usr/bin/bowtie2"                 # or env path
  index: "design/MM10_HindIII/mm10"               # prefix (no .bt2)
  digest: "design/MM10_HindIII/MM10_HindIII_digest.txt"
  format: ""                                      # let HiCUP auto-detect
  longest: 2000
  shortest: 100
  threads: 4
  quiet: 1
  keep: 0
  zip: 0

tools:
  rscript: "Rscript"
  hicup: "hicup"                           # in PATH or full path
  bedtools: "bedtools"
  perl: "perl"
  bam_to_fragments: "scripts/BamToFragments.pl"
  bam2juicer: "scripts/Bam2Juicer.pl"
  align2ibed: "scripts/align2ibed.pl"
  java: "java"
  juicer_tools: "juicer_tools.jar"

params:
  juicer_mem_gb: 10
  juicer_q: 10
  juicer_genome_id: "mm10"
  fanc_resolution: "10kb"
  fanc_balancing: "KR"
  fanc_windows: ["0.5mb","1mb","1.5mb","2mb","2.5mb"]

threads:
  default: 4
